### ISSUE TITLE
Keeping passwords safe

### ISSUE THREAD

**Issue by damien-git** [blueriver/docker-muracms#1]
I am new to Docker and have been experimenting with it and Mura 7.1 using the example files you provided. Overall it's working well, but one particular issue worries me: there are passwords in the docker-compose.yml file which are convenient for testing, but end up as environment variables in the container.
So as a Mura page editor, I can write something like `[m]createObject('java', 'java.lang.System').getenv('MURA_DBPASSWORD')[/m]` to get the database password without having any administrator right.
You warn that these files are not meant for production, but I wonder what I should do in practice: I can't easily change the database password from the Mura UI, so how could I set that after installation without running commands in the container ?

**Comment by stevewithington** [comment]
@damien-git, 

The environment variables are simply `settings.ini.cfm` variables ... so, if you want to set your password in the file there, you can do that instead. Another option would be to set your DSN via the CF Administrator, and then create a new container image based on that. Then, there's no reason to pass that information in. There's other ways to do it as well ... but those are probably the easiest ways to do it. 

That said, if someone has direct access to your container, you've got bigger issues to worry about. Keep in mind this kind of deployment is not the same as a traditional hosting/shared-hosting/deployment scenario either. I hope this makes sense.

**Comment by damien-git** [comment]
Using [docker secrets](https://docs.docker.com/engine/swarm/secrets/) would be a better option, but I think that would require Mura to handle something like MURA_DBPASSWORD_FILE to read the password in a file, and it also requires using a swarm. The problem when using docker is to avoid having passwords in an image (which is [not safe](https://medium.com/@mccode/dont-embed-configuration-or-secrets-in-docker-images-7b2e0f916fdd)) while keeping it easy to use images to replicate environments.

Another issue is clear-text passwords in a file. Ideally that should never happen anywhere.

But I am realizing anything can be done with Mura tags anyway, regardless of docker usage. So one can get the clear text password with something like `[m]$.globalConfig('dbpassword')[/m]` or by looking at the `application` struct... I wish there was a way for editors and template authors to access some of Mura's features without getting a full access to the VM...

**Comment by stevewithington** [comment]
Sure, docker secrets is definitely a great option ... and most production deployments I've been involved with use swarm anyway. Again, if you have the datasource defined in your CF Administrator and create your image on that, but don't allow anyone access to the CF Administrator, you should be good for most purposes when it comes to editors & template authors. When done in this way, I don't see it as technically embedding the password per se, as it's just part of the configuration. In any event, thanks for sharing!
